name: spike
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=22.0
  - numpy
  - requests
  - joblib
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - pyarrow
  - scikit-learn
  - networkx
  - hdbscan
  - numba
  - jupyter
  - pyqt=5
  - pyqtgraph
  - pip:
    - spikeinterface[full,widgets]>=0.99
    - elephant
    - viziphant
    - pyocclient
