[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "Intro-to-Neural-Spike-Analysis-in-Python"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
elephant = { version = ">=1.1.1, <2", extras = ["extras"] }
viziphant = ">=0.4.0, <0.5"


