[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "Intro-to-Neural-Spike-Analysis-in-Python"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pyarrow = ">=20.0.0,<21"
scikit-learn = ">=1.6.1,<2"
ipykernel = ">=6.29.5,<7"
numpy = ">=2.2.6,<3"
scipy = ">=1.15.2,<2"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
elephant = ">=1.0.0, <2"
viziphant = ">=0.4.0, <0.5"
pyocclient = ">=0.6, <0.7"
spikeinterface = { version = ">=0.102.3, <0.103", extras = ["full"] }
